---
external_secrets_helm_repo_url: https://charts.external-secrets.io
external_secrets_helm_repo_name: external-secrets
external_secrets_helm_chart: "{{ external_secrets_helm_repo_name }}/external-secrets"
external_secrets_helm_chart_version: v1.2.1

external_secrets_namespace: external-secrets
